version: '3'
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_DB=testdb"
      - "POSTGRES_USER=testuser"
      - "POSTGRES_PASSWORD=testpassword"
    expose:
      - 5432

  app:
    build:
      context: image
    volumes:
      - ..:/repo
    environment:
      PIPENV_CACHE_DIR: /repo/.cache
      PIPENV_VENV_IN_PROJECT: 1
      VIRTUALENV_ALWAYS_COPY: 1
      CI: 1
      TEST_DATABASE_URL: postgres://testuser:testpassword@db:5432/testdb
    depends_on:
      - db
    working_dir: /repo/
    entrypoint: ["/wait-for-it.sh", "db:5432", "--"]
